apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-yamls
  namespace: argocd
spec:
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: k8s/main/yamls
    repoURL: git@github.com:rootsh/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true